In [66]:
import pandas as pd
import tensorflow as tf
import numpy as np
from tensorflow.keras.models import load_model
import pickle

In [67]:
# load the trained model,scaler pickle,ohe

In [68]:
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [69]:
# load the encoder and scaler

In [70]:
with open('le.pkl','rb') as file:
    labelencoder_gender=pickle.load(file)

with open('ohe_geo.pkl','rb') as file:
    ohe_geography=pickle.load(file)
    
with open('sscaler.pkl','rb') as file:
    standard_scaler=pickle.load(file)

In [71]:
input_data = {
    'CreditScore' : 600,
    'Geography' : 'France',
    'Gender' : 'Male',
    'Age' : 40,
    'Tenure' : 3,
    'Balance' : 60000,
    'NumOfProducts' : 2,
    'HasCrCard' : 1,
    'IsActiveMember' : 1,
    'EstimatedSalary' : 50000
}

In [72]:
geo_encoded=ohe_geography.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=ohe_geography.get_feature_names_out(['Geography']))
geo_encoded_df

d:\GIT_CLONE\Kri_Na_ML_DL\ANN\ANN Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [73]:
# converting dict to df 
input_data_df=pd.DataFrame([input_data])
input_data_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [74]:
# combining ohe columns with input data
input_data=pd.concat([input_data_df.reset_index(drop=True),geo_encoded_df],axis=1)
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,France,Male,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [75]:
input_data['Gender']=labelencoder_gender.transform(input_data['Gender'])

In [77]:
input_df=input_data.drop(['Geography'],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [80]:
# scaling the input data
input_scaled=standard_scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [81]:
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step

array([[0.03775707]], dtype=float32)

In [83]:
probability=prediction[0][0]
probability

np.float32(0.03775707)

In [84]:
if probability > 0.5:
    print("The customer is likely to churn")
else:
    print("The customer is not likely to churn")

The customer is not likely to churn