In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
import pickle

In [2]:
data=pd.read_csv("D:\GIT_CLONE\Kri_Na_ML_DL\ANN\ANN Classification\Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

## Preprocessing the data

In [3]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

## Encode Categorical Variable

In [4]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [5]:
# OHE for geography
ohe_geography=OneHotEncoder(handle_unknown='ignore')
ohe_geo=ohe_geography.fit_transform(data[['Geography']]).toarray()
ohe_geo_df=pd.DataFrame(ohe_geo,columns=ohe_geography.get_feature_names_out(['Geography']))
ohe_geo_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
data=pd.concat([data.drop('Geography',axis=1),ohe_geo_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

## Splitting our data into independent and dependent

In [7]:
X=data.drop(['EstimatedSalary'],axis=1)
y=data['EstimatedSalary']
print(X.shape,y.shape)

(10000, 12) (10000,)

In [8]:
# Split the data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
# Standard Scaler
sscaler_x=StandardScaler()   
X_train=sscaler_x.fit_transform(X_train)
X_test=sscaler_x.transform(X_test)

In [10]:
# saving encoders into pickle
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('ohe_geography.pkl','wb') as file:
    pickle.dump(ohe_geography,file)

with open('sscaler_x.pkl','wb') as file:
    pickle.dump(sscaler_x,file)

In [11]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CreditScore        10000 non-null  int64
 1   Gender             10000 non-null  int64
 2   Age                10000 non-null  int64
 3   Tenure             10000 non-null  int64
 4   Balance            10000 non-null  float64
 5   NumOfProducts      10000 non-null  int64
 6   HasCrCard          10000 non-null  int64
 7   IsActiveMember     10000 non-null  int64
 8   EstimatedSalary    10000 non-null  float64
 9   Exited             10000 non-null  int64
 10  Geography_France   10000 non-null  float64
 11  Geography_Germany  10000 non-null  float64
 12  Geography_Spain    10000 non-null  float64
dtypes: float64(5), int64(8)
memory usage: 1015.8 KB

In [12]:
data.shape

(10000, 13)

## ANN Regression problem statement

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),  # Keras expects input_shape to be a tuple so we give for eg: (12,)
    Dense(32,activation='relu'),
    Dense(1) # here we are not giving activation because by default for activation fun for regression is linear regression
])

d:\GIT_CLONE\Kri_Na_ML_DL\ANN\ANN Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
# Compile the model
model.compile(optimizer='Adam',loss=['mean_absolute_error'],metrics=['mae'])

model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

# Setup tensorboard
log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
Tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [17]:
# Setup Callback
earlystopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [18]:
# train the model
history=model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[Tensorboard_callback,earlystopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - loss: 100398.3828 - mae: 100398.3828 - val_loss: 98589.2891 - val_mae: 98589.2891
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 99859.6016 - mae: 99859.6016 - val_loss: 97457.3672 - val_mae: 97457.3672
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 97817.0703 - mae: 97817.0703 - val_loss: 94399.7266 - val_mae: 94399.7266
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 93647.6328 - mae: 93647.6328 - val_loss: 89109.3594 - val_mae: 89109.3594
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 87343.5469 - mae: 87343.5469 - val_loss: 81933.7812 - val_mae: 81933.7812
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 79462.5625 - mae: 79462.5625 - val_loss: 73754.8672 - val_mae: 73754.8672
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 71117.1094 - mae: 71117.1094 - val_loss: 65952.4141 - val_mae: 65952.4141
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 63541.4258 - mae: 63541.4258 - val_loss: 59477.7461 - val_mae: 59477.7461
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 57731.8867 - mae: 57731.8867 - val_loss: 54985.2227 - val_mae: 54985.2227
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 53962.9922 - mae: 53962.9922 - val_loss: 52361.1445 - val_mae: 52361.1445
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51802.9258 - mae: 51802.9258 - val_loss: 51160.7656 - val_mae: 51160.7656
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50790.5898 - mae: 50790.5898 - val_loss: 50751.7617 - val_mae: 50751.7617
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50395.4688 - mae: 50395.4688 - val_loss: 50613.9414 - val_mae: 50613.9414
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50223.4375 - mae: 50223.4375 - val_loss: 50567.0703 - val_mae: 50567.0703
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50126.6367 - mae: 50126.6367 - val_loss: 50526.5469 - val_mae: 50526.5469
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50061.3203 - mae: 50061.3203 - val_loss: 50496.7773 - val_mae: 50496.7773
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50014.8438 - mae: 50014.8438 - val_loss: 50471.7070 - val_mae: 50471.7070
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49975.9688 - mae: 49975.9688 - val_loss: 50453.5508 - val_mae: 50453.5508
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49943.9258 - mae: 49943.9258 - val_loss: 50434.7188 - val_mae: 50434.7188
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49913.6914 - mae: 49913.6914 - val_loss: 50414.2773 - val_mae: 50414.2773
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49884.1289 - mae: 49884.1289 - val_loss: 50394.4219 - val_mae: 50394.4219
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49856.9023 - mae: 49856.9023 - val_loss: 50380.1992 - val_mae: 50380.1992
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49831.6602 - mae: 49831.6602 - val_loss: 50369.5312 - val_mae: 50369.5312
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49808.8906 - mae: 49808.8906 - val_loss: 50347.0781 - val_mae: 50347.0781
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49788.9727 - mae: 49788.9727 - val_loss: 50342.5117 - val_mae: 50342.5117
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49769.6836 - mae: 49769.6836 - val_loss: 50331.8828 - val_mae: 50331.8828
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49753.1445 - mae: 49753.1445 - val_loss: 50323.1719 - val_mae: 50323.1719
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49731.8203 - mae: 49731.8203 - val_loss: 50322.0430 - val_mae: 50322.0430
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49717.6680 - mae: 49717.6680 - val_loss: 50308.2422 - val_mae: 50308.2422
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49700.9375 - mae: 49700.9375 - val_loss: 50304.1094 - val_mae: 50304.1094
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49685.1523 - mae: 49685.1523 - val_loss: 50309.1484 - val_mae: 50309.1484
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49670.1484 - mae: 49670.1484 - val_loss: 50300.2188 - val_mae: 50300.2188
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49657.1367 - mae: 49657.1367 - val_loss: 50290.2969 - val_mae: 50290.2969
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49642.2266 - mae: 49642.2266 - val_loss: 50289.1953 - val_mae: 50289.1953
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49633.3047 - mae: 49633.3047 - val_loss: 50291.4102 - val_mae: 50291.4102
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49621.7930 - mae: 49621.7930 - val_loss: 50281.4102 - val_mae: 50281.4102
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49606.8711 - mae: 49606.8711 - val_loss: 50287.4844 - val_mae: 50287.4844
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49598.6562 - mae: 49598.6562 - val_loss: 50285.3594 - val_mae: 50285.3594
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49590.8828 - mae: 49590.8828 - val_loss: 50287.7773 - val_mae: 50287.7773
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49582.1992 - mae: 49582.1992 - val_loss: 50281.2578 - val_mae: 50281.2578
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49571.7812 - mae: 49571.7812 - val_loss: 50275.6602 - val_mae: 50275.6602
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49559.9609 - mae: 49559.9609 - val_loss: 50277.9375 - val_mae: 50277.9375
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49549.5859 - mae: 49549.5859 - val_loss: 50269.1055 - val_mae: 50269.1055
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49545.4883 - mae: 49545.4883 - val_loss: 50267.3008 - val_mae: 50267.3008
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49532.6992 - mae: 49532.6992 - val_loss: 50270.8477 - val_mae: 50270.8477
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49527.3750 - mae: 49527.3750 - val_loss: 50267.6836 - val_mae: 50267.6836
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49521.8125 - mae: 49521.8125 - val_loss: 50261.1602 - val_mae: 50261.1602
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49511.7148 - mae: 49511.7148 - val_loss: 50269.2148 - val_mae: 50269.2148
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49503.9805 - mae: 49503.9805 - val_loss: 50262.9336 - val_mae: 50262.9336
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49498.7773 - mae: 49498.7773 - val_loss: 50272.7930 - val_mae: 50272.7930
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49488.1875 - mae: 49488.1875 - val_loss: 50269.9336 - val_mae: 50269.9336
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49482.7969 - mae: 49482.7969 - val_loss: 50277.2188 - val_mae: 50277.2188
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49475.9062 - mae: 49475.9062 - val_loss: 50267.6484 - val_mae: 50267.6484
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49472.7344 - mae: 49472.7344 - val_loss: 50260.3086 - val_mae: 50260.3086
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49468.6367 - mae: 49468.6367 - val_loss: 50269.8359 - val_mae: 50269.8359
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49457.8359 - mae: 49457.8359 - val_loss: 50275.1250 - val_mae: 50275.1250
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49452.0195 - mae: 49452.0195 - val_loss: 50276.2461 - val_mae: 50276.2461
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49448.7578 - mae: 49448.7578 - val_loss: 50275.8477 - val_mae: 50275.8477
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49440.0156 - mae: 49440.0156 - val_loss: 50273.6055 - val_mae: 50273.6055
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49437.0703 - mae: 49437.0703 - val_loss: 50278.5352 - val_mae: 50278.5352
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49431.4102 - mae: 49431.4102 - val_loss: 50273.5039 - val_mae: 50273.5039
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49429.5586 - mae: 49429.5586 - val_loss: 50285.3438 - val_mae: 50285.3438
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49422.6914 - mae: 49422.6914 - val_loss: 50286.3203 - val_mae: 50286.3203
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49419.1211 - mae: 49419.1211 - val_loss: 50284.1602 - val_mae: 50284.1602

In [19]:
%load_ext tensorboard
%tensorboard --logdir regressionlogs/fit

Launching TensorBoard...

In [20]:
# Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f"Test mae is {test_mae:.2f}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50260.3086 - mae: 50260.3086
Test mae is 50260.31

In [21]:
model.save('regressionmodel.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [22]:
# Streamlit is not created for regression problem